@startuml cas_dutilisations
title Cas d'utilisations

left to right direction

actor Application as app
actor Appareil as user

package XRTouch {
    usecase "changer la force de retour" as hapticSend
    usecase "recuperer la force de retour" as hapticRecv
    usecase "changer la position de l'appareil" as actionSend
    usecase "recuperer la position de l'appareil" as actionRecv
}

app -[#red]> hapticSend
app -[#red]> actionRecv
user -[#blue]> actionSend
user -[#blue]> hapticRecv

@enduml